---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-v3
  region: ap-south-1
  version: "1.18"
vpc:
  id: vpc-00312e38efdfa7c0b
  subnets:
    public:
      public-1a:
        id: subnet-0934fd169f7e954c2
      public-1b:
        id: subnet-0ce7950c8f11b4cfb
      public-1c:
        id: subnet-0159ef437eb5d2006
    private:
      private-1a:
        id: subnet-0046aa57d77ed0f3c
      private-1b:
        id: subnet-0ce0add7fb8cf209f
      private-1c:
        id: subnet-0bc54c60b6b1519df
#nodeGroups:
#  - name: general-v2
#    labels:
#      role: general
#    instanceType: t3.small
#    desiredCapacity: 1
#    privateNetworking: true
#    ssh:
#      publicKeyName: devops
#    subnets:
#      - private-1a
#      - private-1b
#      - private-1c
#  - name: spot-v2
#    labels:
#      role: spot
#    minSize: 1
#    maxSize: 1
#    instancesDistribution:
#      instanceTypes:
#        - t3.small
#      onDemandBaseCapacity: 0
#      onDemandPercentageAboveBaseCapacity: 0
#      spotInstancePools: 20
#    privateNetworking: true
##    taints:
##      spot: "true:NoSchedule"
#    subnets:
#      - private-1a
#      - private-1b
#      - private-1c
managedNodeGroups:
  - name: managed
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
    subnets:
      - private-1a
      - private-1b
      - private-1c