---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: uniclub-poc
  region: ap-south-1
  version: "1.18"
vpc:
  id: vpc-0bb866b8b68990123
  subnets:
    public:
      public-1a:
        id: subnet-052c9fe2167b38f6d
      public-1b:
        id: subnet-0e9de06978d31bbce
#      public-1c:
#        id: subnet-0159ef437eb5d2006
    private:
      private-1a:
        id: subnet-0eb2520f43233d9fa
      private-1b:
        id: subnet-0292597e895086af0
#      private-1c:
#        id: subnet-0bc54c60b6b1519df
#nodeGroups:
#  - name: general-v2
#    labels:
#      role: general
#    instanceType: t3.small
#    desiredCapacity: 1
#    privateNetworking: true
#    ssh:
#      publicKeyName: devops
#    subnets:
#      - private-1a
#      - private-1b
#      - private-1c
#  - name: spot-v2
#    labels:
#      role: spot
#    minSize: 1
#    maxSize: 1
#    instancesDistribution:
#      instanceTypes:
#        - t3.small
#      onDemandBaseCapacity: 0
#      onDemandPercentageAboveBaseCapacity: 0
#      spotInstancePools: 20
#    privateNetworking: true
##    taints:
##      spot: "true:NoSchedule"
#    subnets:
#      - private-1a
#      - private-1b
#      - private-1c
managedNodeGroups:
  - name: managed
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
    subnets:
      - private-1a
      - private-1b
#      - private-1c
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
#        appMesh: true
#        appMeshPreview: true
        ebs: true
#        fsx: true
#        efs: true
        albIngress: true
#        xRay: true
        cloudWatch: true
